---
title: "Digit Recognizer"
author: "Carolyn"
date: "November 21, 2015"
output: html_document
---

The goal in this competition is to take an image of a handwritten single digit, and determine what that digit is. For more details see <https://www.kaggle.com/c/digit-recognizer>.

1. Setting the working directory.
```{r}
wd<-'D:/Data Science/kaggle/Digit Recognizer'
if(getwd()!=wd){
  setwd(wd)
}
```

2. Setting up libraries.
```{r, warning=FALSE}
library(readr)
library(ggplot2)
library(proto)
library(caret)
```

3. Get data into R.
```{r}
train<-read.csv('train.csv')
test<-read.csv('test.csv')
cat(sprintf("Training set has %d rows and %d columns\n", nrow(train), ncol(train)))
cat(sprintf("Test set has %d rows and %d columns\n", nrow(test), ncol(test)))
```

4.Example Handwritten Digit
```{R}
labels   <- train[,1]
features <- train[,-1]

set.seed(1)
rowsToPlot <- sample(1:nrow(train), 1)

rowToMatrix <- function(row) {
    intensity <- as.numeric(row)/max(as.numeric(row))
    return(t(matrix((rgb(intensity, intensity, intensity)), 28, 28)))
}

geom_digit <- function (digits, labels) GeomRasterDigit$new(geom_params = list(digits=digits),
  stat = "identity", position = "identity", data = NULL, inherit.aes = TRUE)

GeomRasterDigit <- proto(ggplot2:::GeomRaster, expr={
  draw_groups <- function(., data, scales, coordinates, digits, ...) {
    bounds <- coord_transform(coordinates, data.frame(x = c(-Inf, Inf), y = c(-Inf, Inf)), scales)
    x_rng <- range(bounds$x, na.rm = TRUE)
    y_rng <- range(bounds$y, na.rm = TRUE)
    rasterGrob(as.raster(rowToMatrix(digits[data$rows,])), x_rng[1], y_rng[1], diff(x_rng), diff(y_rng), 
               default.units = "native", just = c("left","bottom"), interpolate = FALSE)
  }
})

p <- ggplot(data.frame(rows=rowsToPlot, labels=labels[rowsToPlot]), aes(x=.1, y=.9, rows=rows, label=labels)) + geom_blank() + xlim(0,1) + ylim(0,1) + xlab("") + ylab("") + 
  #facet_wrap(~ rows, ncol=7) +
  geom_digit(features) +
  geom_text(colour="#53cfff") +
  theme(strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank()) +
  ggtitle("Example Handwritten Digit")

ggsave("example_digit.png", p, width=10, height=10)
```

5.Random Forest Benchmark
```{r}
modFit <- train(label~ ., data = train, method = 'rf', prox = TRUE)
modFit
```